config/routes.rb
Tracklist::Application.routes.draw do
  resources :tags

  resources :tracks
  resources :authors

  resources :albums

  root :to => 'albums#index'

end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :album
  belongs_to :author
  has_many :taglinks, as: :resource
  has_many :tags, through: :taglinks
  has_attached_file :song
  attr_accessible :album_id, :author_id, :track_number, :title, :token_inputs, :song
  validates :title, :album, :author, presence: true 

  attr_reader :token_inputs
  def token_inputs=(names)
    names.split(",").each do |name|
      name.slice!("New: ")
      self.tags << Tag.find_or_create_by_name(name.delete('"'))
    end
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  # GET /tracks
  # GET /tracks.json
  def index
    @search = Track.search(params[:q])
    @tracks = @search.result


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tracks }
    end
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
    @track = Track.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @track }
    end
  end

  # GET /tracks/new
  # GET /tracks/new.json
  def new
    @track = Track.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @track }
    end
  end

  # GET /tracks/1/edit
  def edit
    @track = Track.find(params[:id])
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(params[:track])

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render json: @track, status: :created, location: @track }
      else
        format.html { render action: "new" }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tracks/1
  # PUT /tracks/1.json
  def update
    @track = Track.find(params[:id])

    respond_to do |format|
      if @track.update_attributes(params[:track])
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track = Track.find(params[:id])
    @track.destroy

    respond_to do |format|
      format.html { redirect_to tracks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.haml
= simple_form_for(@track) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :token_inputs,label: "Tags:", input_html: { data:{ load: @track.tags} }
    = f.association :author
    = f.file_field :song
    = f.input :track_number
    = f.association :album



  .form-actions
    = f.button :submit

app/views/tracks/edit.html.haml
%h1 Editing track

= render 'form'

= link_to 'Show', @track
\|
= link_to 'Back', tracks_path

app/views/tracks/index.html.haml
-content_for :search do
  = search_form_for @search, html: {class: 'navbar-search pull-right'} do |s|
    = s.text_field :title_cont, class: 'search-query', placeholder: "Search"

%h1 TRACKS

%br

%table
  %tr
    %th Title
    %th Tags
    %th Author
    %th track_number
    %th Album
    %th
    %th
    %th

  - @tracks.each do |track|
    %tr
      %td= track.title
      %td= tags_links(track)
      %td= link_to track.author.name, author_path(track.author)
      %td= track.track_number
      %td= link_to track.album.title, album_path(track.album)
      %td
        = link_to track, class: "btn btn-small btn" do
          %i.icon-eye-open
          Show
      %td
        = link_to edit_track_path(track), class: "btn btn-small btn" do
          %i.icon-pencil
          Edit
      %td
        = link_to track, class: "btn btn-small btn", :confirm => 'Are you sure?', :method => :delete do
          %i.icon-trash
          Destroy

%br

= link_to new_track_path, class: "btn btn-small btn-success" do
  %i.icon-plus
  New Track

app/views/tracks/new.html.haml
%h1 New track

= render 'form'

= link_to 'Back', tracks_path

app/views/tracks/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @track.title
%p
  %b Tag:
  = tags_links(@track)
%p
  %b Author:
  = @track.author.name
%p
  %b T_number:
  = @track.track_number
%p
  %b Album:
  = @track.album.title
%p
  %b Song:
  =audio_tag @track.song.url, controls: true
  
= link_to 'Edit', edit_track_path(@track)
\|
= link_to 'Back', tracks_path