config/routes.rb
Tracklist::Application.routes.draw do
  resources :tags

  resources :tracks
  resources :authors

  resources :albums

  root :to => 'albums#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :albums
  has_many :tracks
  has_many :taglinks, as: :resource
  has_many :tags, through: :taglinks
  attr_accessible :description, :name, :token_inputs
  validates :name, presence: true
  attr_reader :token_inputs
  def token_inputs=(names)
    names.split(",").each do |name|
      name.slice!("New: ")
      self.tags << Tag.find_or_create_by_name(name.delete('"'))
    end
  end 
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.json
  def index
    @search = Author.search(params[:q])
    @authors = @search.result


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.haml
= simple_form_for(@author) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :token_inputs,label: "Tags:", input_html: { data:{ load: @author.tags} }

  .form-actions
    = f.button :submit 
    
 

app/views/authors/edit.html.haml
%h1 Editing author

= render 'form'

= link_to 'Show', @author
\|
= link_to 'Back', authors_path

app/views/authors/index.html.haml
-content_for :search do
  = search_form_for @search, html: {class: 'navbar-search pull-right'} do |s|
    = s.text_field :name_cont, class: 'search-query', placeholder: "Search"

%h1 AUTHORS

%table
  %tr
    %th Name
    %th Description
    %th Tag
    %th
    %th
    %th

  - @authors.each do |author|
    %tr
      %td= author.name
      %td= author.description
      %td= tags_links(author)
      %td
        = link_to author, class: "btn btn-small btn" do
          %i.icon-eye-open
          Show
      %td
        = link_to edit_author_path(author), class: "btn btn-small btn" do
          %i.icon-pencil
          Edit
      %td
        = link_to author, class: "btn btn-small btn", :confirm => 'Are you sure?', :method => :delete do
          %i.icon-trash
          Destroy

%br

= link_to new_author_path, class: "btn btn-small btn-success" do
  %i.icon-hand-up
  New Author

app/views/authors/new.html.haml
%h1 New author

= render 'form'

= link_to 'Back', authors_path

app/views/authors/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @author.name
%p
  %b Description:
  = @author.description
%p
  %b Tag:
  = tags_links(@author)
 
= link_to 'Edit', edit_author_path(@author)
\|
= link_to 'Back', authors_path


%h1 Listing albums

%table
  %tr
    %th Title
    %th Description
    %th Tag
    %th
    %th
    %th

  - @author.albums.each do |album|
    %tr
      %td= album.title
      %td= album.description
      %td= tags_links(album)
      %td= link_to 'Show', album
      %td= link_to 'Edit', edit_album_path(album)
      %td= link_to 'Destroy', album, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Album', new_album_path