config/routes.rb
Tracklist::Application.routes.draw do
  resources :tags

  resources :tracks
  resources :authors

  resources :albums

  root :to => 'albums#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :author
  has_many :tracks, :order => 'track_number ASC'
  has_many :taglinks, as: :resource
  has_many :tags, through: :taglinks
  has_attached_file :cover
  attr_accessible :author_id, :description, :tag_id, :title, :token_inputs, :cover
  validates :title, :author, presence: true
  attr_reader :token_inputs

  def token_inputs=(names)
    names.split(",").each do |name|
      name.slice!("New: ")
      self.tags << Tag.find_or_create_by_name(name.delete('"'))
    end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # GET /albums
  # GET /albums.json
  def index
    @search = Album.search(params[:q])
    @albums = @search.result

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.haml
= simple_form_for @album do |f|
  -if @album.errors.any?
    #error_explanation
      %h2= "#{pluralize(@album.errors.count, "error")} prohibited this album from being saved:"
      %ul
        - @album.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.input :title
  .field
    = f.input :description
  .field
    = f.input :token_inputs,label: "Tags:", input_html: { data:{ load: @album.tags} }
  .field 
    = f.file_field :cover
  .field
    = f.association :author
  .actions
    = f.submit 'Save'

app/views/albums/edit.html.haml
%h1 Editing album

= render 'form'

= link_to 'Show', @album
\|
= link_to 'Back', albums_path

app/views/albums/index.html.haml
-content_for :search do
  = search_form_for @search, html: {class: 'navbar-search pull-right'} do |s|
    = s.text_field :title_cont, class: 'search-query', placeholder: "Search"


%h1.title ALBUMS
  
%br

- @albums.each do |album|
  %ul.row
    %li.span6
      .span2
        %p
          =image_tag @album.cover.url
      .span4
        %div
          = album.title
          = link_to album, class: "btn btn-small btn pull-right" do
            %i.icon-eye-open
        %div 
          = link_to album.author.name, author_path(album.author)
          = link_to edit_album_path(album), class: "btn btn-small btn pull-right" do
            %i.icon-pencil
        %div
          = tags_links(album)
          = link_to album, class: "btn btn-small btn pull-right", :confirm => 'Are you sure?', :method => :delete do
            %i.icon-trash

%br

= link_to new_album_path, class: "btn btn-small btn-success" do
  %i.icon-hand-up
  New Album

app/views/albums/new.html.haml
%h1 New album

= render 'form'

= link_to 'Back', albums_path

app/views/albums/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @album.title
%p
  %b Description:
  = @album.description
%p
  %b Tag:
  = tags_links(@album)
   
%p
  %b Author:
  = @album.author_id

%p
  %b Cover:
  =image_tag @album.cover.url

= link_to 'Edit', edit_album_path(@album)
\|
= link_to 'Back', albums_path

%h1 Listing tracks

%table
  %tr
    %th Title
    %th Tag
    %th Author
    %th track_number
    %th Album
    %th
    %th
    %th

  - @album.tracks.each do |track|
    %tr
      %td= track.title
      %td= tags_links(track)
      %td= link_to track.author.name, author_path(track.author)
      %td= link_to track.track_number
      %td= track.tags.map {|x| (link_to x.name,x)}.join(", ").html_safe
      %td= link_to track.album.title, album_path(track.album)
      %td= link_to 'Show', track
      %td= link_to 'Edit', edit_track_path(track)
      %td= link_to 'Destroy', track, :confirm => 'Are you sure?', :method => :delete

= link_to 'New Track', new_track_path